<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
    </PropertyGroup>

    <!-- 
    Esto lo agregue a mano para poder hacer una librería de clases y que tenga Microsoft.AspNetCore.App.
    La otra opción es hacer un proyecto de API y borrar todo.
    Microsoft.AspNetCore.App no se instala como paquete de Nugget.
    -->
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\Core\My.Exceptions\My.Exceptions.csproj" />
        <ProjectReference Include="..\..\..\Core\My.System.Extensions\My.System.Extensions.csproj" />
        <ProjectReference Include="..\Records.Shared.Contracts\Records.Shared.Contracts.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1" />
    </ItemGroup>
</Project>
