<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Scrutor" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Records.Shared.Cqrs.Abstractions\Records.Shared.Cqrs.Abstractions.csproj" />
    <ProjectReference Include="..\Records.Shared.Cqrs\Records.Shared.Cqrs.csproj" />
  </ItemGroup>

</Project>
