<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.16.20" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Modules\Persons\Records.Persons.Application\Records.Persons.Application.csproj" />
      <ProjectReference Include="..\..\Modules\Persons\Records.Persons.Infra.Configuration.DependencyInjection\Records.Persons.Infra.Configuration.DependencyInjection.csproj" />
      <ProjectReference Include="..\..\Modules\Persons\Records.Persons.Shared.Configuration\Records.Persons.Shared.Configuration.csproj" />
      <ProjectReference Include="..\..\Modules\Shared\Shared.Application.DependencyInjection\Shared.Application.DependencyInjection.csproj" />
      <ProjectReference Include="..\..\Modules\Shared\Shared.Contracts\Shared.Contracts.csproj" />
      <ProjectReference Include="..\..\Modules\Shared\Shared.Mediator.DependencyInjection\Shared.Mediator.DependencyInjection.csproj" />
      <ProjectReference Include="..\..\Modules\Shared\Shared.Infra.Http.DependencyInjection\Shared.Infra.Http.DependencyInjection.csproj" />
      <ProjectReference Include="..\..\Modules\Shared\Shared.Infra.Http\Shared.Infra.Http.csproj" />
      <ProjectReference Include="..\..\Modules\Shared\Shared.Infra.OpenApi.DependencyInjection\Shared.Infra.OpenApi.DependencyInjection.csproj" />
      <ProjectReference Include="..\..\Modules\Shared\Shared.Infra.Serilog.DependencyInjection\Shared.Infra.Serilog.DependencyInjection.csproj" />
    </ItemGroup>

</Project>
