<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.0" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\Records.Persons.Shared.Configuration\Records.Persons.Shared.Configuration.csproj" />
    </ItemGroup>

</Project>
