<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Scrutor" Version="7.0.0" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\Shared.Infra.Http\Shared.Infra.Http.csproj" />
    </ItemGroup>
    
</Project>
